variant: prices
network:
    type: csv
    index: i2.csv
    threshold: 1000
    file: data_2009.csv
transport:
  file: transit_times.csv
  index: indices.csv
  type: csv
parameters:
  always_extend_expected_demand_curve: false
  cheapest_price_range_width: auto
  cost_correction: false
  transport_penalty_large: 0.08
  transport_penalty_small: 0.08
  delta_t: 1
  maximal_decrease_reservation_price_limited_by_markup: false
  min_storage: 0
  naive_expectations: true
  no_self_supply: true
  optimization_algorithm: slsqp
  optimization_maxiter: 500000
  optimization_timeout: 40
  quadratic_storage_penalty: false
  quadratic_transport_penalty: true
  relative_transport_penalty: true
  storage_penalty_large: 0.05
  storage_penalty_small: 0.15
firm:
  - possible_overcapacity_ratio: 1.1
sector:
  - consumption_price_elasticity: -0.5
    initial_storage_fill_factor: 15
    initial_markup: 0.05
    price_increase_production_extension: 5.0
    supply_elasticity: 0.05
    target_storage_refill_time: 2
    target_storage_withdraw_time: 2
    upper_storage_limit: 3.0
scenario:
  type: events
  start: 0
  stop: 30
  events:
    - from: 1
      to: 3
      type: shock
      targets:
        - firm:
            region: JPN
            sector: MACH
            remaining_capacity: 0.01
outputs:
  - file: output.nc
    format: netcdf
    flush: 1
    observables:
      - agent:
          parameters:
            - production
      - meta:
          parameters:
            - duration
