if(NETCDF_FORTRAN_INCLUDE_DIR AND NETCDF_FORTRAN_LIBRARY)
  set(NETCDF_FORTRAN_FIND_QUIETLY TRUE)
endif()

find_path(NETCDF_FORTRAN_INCLUDE_DIR NAMES netcdf.mod)
find_library(NETCDF_FORTRAN_LIBRARY NAMES netcdff)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(NETCDF_FORTRAN DEFAULT_MSG NETCDF_FORTRAN_INCLUDE_DIR NETCDF_FORTRAN_LIBRARY)

mark_as_advanced(NETCDF_FORTRAN_INCLUDE_DIR NETCDF_FORTRAN_LIBRARY)

set(NETCDF_FORTRAN_LIBRARIES ${NETCDF_FORTRAN_LIBRARY} )
set(NETCDF_FORTRAN_INCLUDE_DIRS ${NETCDF_FORTRAN_INCLUDE_DIR} )

if(NETCDF_FORTRAN_FOUND AND NOT TARGET netcdff)
  add_library(netcdff UNKNOWN IMPORTED)
  set_target_properties(netcdff PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${NETCDF_FORTRAN_INCLUDE_DIRS}")
  set_target_properties(netcdff PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES "Fortran")
  set_target_properties(netcdff PROPERTIES IMPORTED_LOCATION "${NETCDF_FORTRAN_LIBRARIES}")
endif()
