basetable:
  index: indices.csv
  file: basetable.csv
  type: csv
  threshold: 0
disaggregation:
  - id: regB
    type: region
    into: [ regB1, regB2 ]
    proxies:
      - level: 1
        year: 2010
        file: proxy1.csv
  - id: secC
    type: sector
    into: [ secC1, secC2 ]
    proxies:
      - level: 8
        year: 2010
        file: proxy2.csv
output:
  file: output.csv
  type: csv
