if(NETCDF_CPP4_INCLUDE_DIR AND NETCDF_CPP4_LIBRARY)
  set(NETCDF_CPP4_FIND_QUIETLY TRUE)
endif()

find_path(NETCDF_CPP4_INCLUDE_DIR NAMES ncFile.h)
find_library(NETCDF_CPP4_LIBRARY NAMES netcdf_c++4)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(NETCDF_CPP4 DEFAULT_MSG NETCDF_CPP4_INCLUDE_DIR NETCDF_CPP4_LIBRARY)

mark_as_advanced(NETCDF_CPP4_INCLUDE_DIR NETCDF_CPP4_LIBRARY)

set(NETCDF_CPP4_LIBRARIES ${NETCDF_CPP4_LIBRARY} )
set(NETCDF_CPP4_INCLUDE_DIRS ${NETCDF_CPP4_INCLUDE_DIR} )

if(NETCDF_CPP4_FOUND AND NOT TARGET netcdf_c++4)
  add_library(netcdf_c++4 UNKNOWN IMPORTED)
  set_target_properties(netcdf_c++4 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${NETCDF_CPP4_INCLUDE_DIR}")
  set_target_properties(netcdf_c++4 PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES "CXX")
  set_target_properties(netcdf_c++4 PROPERTIES IMPORTED_LOCATION "${NETCDF_CPP4_LIBRARY}")
endif()
