# SPDX-FileCopyrightText: Acclimate authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: install netcdf
      run: sudo apt-get install libnetcdf-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror -Wno-nonnull" -DCXX_WARNINGS=ON .. 
    - name: build
      run: cmake --build build
